name: ahmad_progress_soft_task
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  flutter_screenutil: ^5.9.3
  firebase_auth: ^5.1.4
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.2
  cloud_firestore: ^5.2.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  equatable: ^2.0.5
  shimmer: ^3.0.0
  pinput: ^5.0.0
  firebase_storage: ^12.1.3

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/visual/png/
