// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu7qPHbU4oxwM0gE50I5p_OA1vNakhqOs',
    appId: '1:473872342168:android:1303fe255871be4e3784ed',
    messagingSenderId: '473872342168',
    projectId: 'ahmad-progresssofttask',
    storageBucket: 'ahmad-progresssofttask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhSDx-fRaNA4jXRsrV9Z9IJMtuuqxERlo',
    appId: '1:473872342168:ios:0393388446e8ebae3784ed',
    messagingSenderId: '473872342168',
    projectId: 'ahmad-progresssofttask',
    storageBucket: 'ahmad-progresssofttask.appspot.com',
    iosBundleId: 'com.example.ahmadProgressSoftTask',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk_1aHLlXby19MV-YUtjwTqnDKgjuVZD8',
    appId: '1:473872342168:web:ffb67559d77a368c3784ed',
    messagingSenderId: '473872342168',
    projectId: 'ahmad-progresssofttask',
    authDomain: 'ahmad-progresssofttask.firebaseapp.com',
    storageBucket: 'ahmad-progresssofttask.appspot.com',
    measurementId: 'G-CCRLMJE7GF',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk_1aHLlXby19MV-YUtjwTqnDKgjuVZD8',
    appId: '1:473872342168:web:2bba5c05067f5dfb3784ed',
    messagingSenderId: '473872342168',
    projectId: 'ahmad-progresssofttask',
    authDomain: 'ahmad-progresssofttask.firebaseapp.com',
    storageBucket: 'ahmad-progresssofttask.appspot.com',
    measurementId: 'G-4Q9DGQS88L',
  );

}